### ISSUE TITLE
error: custom attribute panicked

### ISSUE THREAD

**Issue by grian32** [littledivy/deno_bindgen#27]
full stack trace:
```rs
error: custom attribute panicked
 --> src/lib.rs:3:1
  |
3 | #[deno_bindgen]
  | ^^^^^^^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)
```

repro code:
```rs
#[deno_bindgen::deno_bindgen]
fn greet() -> i32 {
    return 42;
}
```

Fixed by deleting `bindings.json` in project root

**Comment by khanhankkhan** [comment]
I'm having this issue come up. Deleting bindings.json (and the bindings/bindings.ts) did not solve for me. 

error: custom attribute panicked
  --> src/lib.rs:13:1
   |
13 | #[deno_bindgen]
   | ^^^^^^^^^^^^^^^
   |
   = help: message: not implemented

the fix for me was to remove the '&' from the function signature, and changed 
```
#[deno_bindgen]
fn my_init(inp:**&**i32) {}
```

to 
```
#[deno_bindgen]
fn my_init(inp:i32) {}

```
